server:
  port: 10809

book:
  path: /root/msgraph/books

#-------------- msgraph configuration --------------------------
#msgraph:
#  tenant:
#  client-id:
#  client-secret:
#  drive-id:
#  user-id: